"use client"
import './globals.css'
import { Kanit } from 'next/font/google'
import React from 'react'
import { NextUIProvider } from '@nextui-org/react';

const kanit = Kanit({ subsets: ['latin', 'thai'], weight: '400' })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
      <html lang="en">
        <NextUIProvider>
          <body className={kanit.className}>{children}</body>
        </NextUIProvider>
      </html>
    
  )
}
