"use client"
import './globals.css'
import { Kanit } from 'next/font/google'
import React from 'react'
import {createTheme, NextUIProvider} from '@nextui-org/react';
import {ThemeProvider as NextThemesProvider} from 'next-themes';
import {Layout} from "../components/layout/layout"

const kanit = Kanit({ subsets: ['latin', 'thai'], weight: '400' })

const lightTheme = createTheme({
  type: 'light',
  theme: {
     colors: {},
  },
});

const darkTheme = createTheme({
  type: 'dark',
  theme: {
     colors: {},
  },
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
      <html lang="en">
        <NextThemesProvider defaultTheme="system" attribute="class" value={{ light: lightTheme.className, dark: darkTheme.className, }} >
          <NextUIProvider>
            <body className={kanit.className}>
              <Layout>
                {children}
              </Layout>
            </body>
          </NextUIProvider>
      </NextThemesProvider>
        
      </html>
    
  )
}